import {
  Inject,
  Injectable,
  Logger,
  NotFoundException,
  OnModuleInit,
} from '@nestjs/common';
import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { InjectModel } from '@nestjs/mongoose';
import type { Cache } from 'cache-manager';
import { Model, Types } from 'mongoose';
import { Ticker, TickerDocument } from './schemas/ticker.schema';
import {
  HistoricalPrice,
  HistoricalPriceDocument,
} from './schemas/historical-price.schema';
import {
  HistoryInterval,
  HistoryQueryDto,
  HistoryRange,
} from './dto/history-query.dto';
import { nextPrice } from '../market-data/price-generator';
import { SEED_TICKERS } from './seed/tickers.seed';

const TICKERS_CACHE_KEY = 'tickers:list';
const TICKERS_CACHE_TTL_MS = 60_000;
const HISTORY_CACHE_TTL_MS = 30_000;

// Historical backfill tuning. The seed `volatility` values are sized
// for sub-second live ticks (1.5%–3.5%). Re-using them at 1-minute
// granularity over 24h compounds into ±20% swings that look like a
// giant wave on a 1h chart instead of normal intraday movement. We
// scale them down for the backfill loop and apply mean-reversion the
// same way the live simulator does, so historical data oscillates
// realistically around base_price.
const BACKFILL_VOLATILITY_SCALE = 0.15;
const BACKFILL_MEAN_REVERSION_STRENGTH = 0.01;
// Self-heal threshold: if any historical point sits more than this
// fraction away from base_price the data was generated by the old
// (drift-less) backfill, so we drop it and regenerate.
const HISTORY_DRIFT_DETECTION_PCT = 0.15;

@Injectable()
export class TickerService implements OnModuleInit {
  private readonly logger = new Logger('TickerService');

  constructor(
    @InjectModel(Ticker.name)
    private readonly tickerModel: Model<TickerDocument>,
    @InjectModel(HistoricalPrice.name)
    private readonly historyModel: Model<HistoricalPriceDocument>,
    @Inject(CACHE_MANAGER) private readonly cache: Cache,
  ) {}

  async onModuleInit() {
    await this.seedTickers();
    await this.healBadHistory();
    await this.backfillHistoryIfEmpty();
  }

  private async seedTickers() {
    // Step 1: heal any existing duplicates first. This is defensive — if two
    // machines booted simultaneously against a fresh DB before the unique
    // index on `symbol` was built, both ran insertMany() and we ended up
    // with 2× rows per symbol. This step removes the extras every boot.
    await this.dedupeTickers();

    // Step 2: idempotent upsert keyed on `symbol`. Safe under concurrent
    // boots because each updateOne is atomic at the document level — even
    // if 10 machines run this in parallel they all converge on the same
    // 6-row state. $setOnInsert ensures we don't overwrite live mutations
    // (e.g. is_active toggles) on existing rows.
    const ops = SEED_TICKERS.map((t) => ({
      updateOne: {
        filter: { symbol: t.symbol },
        update: { $setOnInsert: t },
        upsert: true,
      },
    }));
    const result = await this.tickerModel.bulkWrite(ops);
    const inserted = result.upsertedCount ?? 0;
    if (inserted > 0) {
      this.logger.log(
        `✅ Seeded ${inserted} new tickers (${SEED_TICKERS.length - inserted} already present)`,
      );
    } else {
      this.logger.log(
        `Tickers already seeded (${SEED_TICKERS.length} present)`,
      );
    }
  }

  private async dedupeTickers() {
    const dupes = await this.tickerModel.aggregate<{
      _id: string;
      ids: Types.ObjectId[];
      count: number;
    }>([
      {
        $group: { _id: '$symbol', ids: { $push: '$_id' }, count: { $sum: 1 } },
      },
      { $match: { count: { $gt: 1 } } },
    ]);
    if (dupes.length === 0) return;

    let totalRemoved = 0;
    for (const group of dupes) {
      // Keep the first id (insertion order), delete the rest.
      const toDelete = group.ids.slice(1);
      const r = await this.tickerModel.deleteMany({ _id: { $in: toDelete } });
      totalRemoved += r.deletedCount ?? 0;
    }
    this.logger.warn(
      `🧹 Removed ${totalRemoved} duplicate ticker rows across ${dupes.length} symbols`,
    );
    // Invalidate any cached /tickers response so the next request reflects
    // the cleaned state immediately.
    await this.cache.del(TICKERS_CACHE_KEY);
  }

  /**
   * If the existing historical data was generated by the old drift-less
   * backfill it will contain points wildly off from base_price. Detect
   * that and wipe the collection so {@link backfillHistoryIfEmpty}
   * regenerates it with realistic mean-reverted prices.
   *
   * Idempotent: once the bad data is gone the regenerated points are
   * within tolerance and this check is a single countDocuments() no-op.
   */
  private async healBadHistory() {
    const tickers = await this.tickerModel.find().lean();
    const symbolsToWipe: string[] = [];
    for (const t of tickers) {
      const lo = t.base_price * (1 - HISTORY_DRIFT_DETECTION_PCT);
      const hi = t.base_price * (1 + HISTORY_DRIFT_DETECTION_PCT);
      const offender = await this.historyModel
        .findOne({
          symbol: t.symbol,
          $or: [{ price: { $lt: lo } }, { price: { $gt: hi } }],
        })
        .lean();
      if (offender) symbolsToWipe.push(t.symbol);
    }
    if (symbolsToWipe.length === 0) return;
    const result = await this.historyModel.deleteMany({
      symbol: { $in: symbolsToWipe },
    });
    this.logger.warn(
      `Wiped ${result.deletedCount} stale historical points for ` +
        `${symbolsToWipe.join(', ')} (drift > ${HISTORY_DRIFT_DETECTION_PCT * 100}% from base_price). ` +
        `They'll be re-backfilled with mean-reverted data.`,
    );
    // Invalidate any cached history responses so the next request reflects
    // the freshly-generated data instead of the bad cached series.
    for (const sym of symbolsToWipe) {
      for (const range of ['1h', '1d', '1w'] as const) {
        for (const interval of ['1m', '5m', '1h'] as const) {
          await this.cache.del(`history:${sym}:${range}:${interval}`);
        }
      }
    }
  }

  private async backfillHistoryIfEmpty() {
    const tickers = await this.tickerModel.find().lean();
    const now = Date.now();
    const MINUTE = 60_000;
    const HOUR = 60 * MINUTE;
    const DAY = 24 * HOUR;

    // Tiered backfill so the chart's range selector (1H / 1D / 1W / 1M
    // / 1Y / 5Y / custom) has sensible data at every zoom level:
    //   - Last 24h : 1-minute granularity  → powers 1H + 1D views
    //   - Last 60d : 1-hour granularity    → powers 1W + 1M views
    //   - Last 5y  : 1-day granularity     → powers 1Y + 5Y views
    const tiers = [
      { stepMs: MINUTE, points: 24 * 60 },
      { stepMs: HOUR, points: 60 * 24 },
      { stepMs: DAY, points: 5 * 365 },
    ];

    const docs: { symbol: string; price: number; timestamp: Date }[] = [];
    for (const ticker of tickers) {
      const existing = await this.historyModel
        .countDocuments({ symbol: ticker.symbol })
        .exec();
      if (existing > 0) continue;

      for (const tier of tiers) {
        // Scale volatility by √(stepMs / 1s) so longer buckets look like
        // longer-term movement instead of compounding per-tick noise
        // into unrealistic waves. Mean-reversion anchors everything to
        // base_price so the series stays recognisable over 5 years.
        const stepScale = Math.sqrt(tier.stepMs / 1000);
        const scaledVol =
          ticker.volatility * BACKFILL_VOLATILITY_SCALE * stepScale;
        let price = ticker.base_price;
        for (let i = tier.points; i >= 0; i--) {
          const drift =
            ((ticker.base_price - price) / price) *
            BACKFILL_MEAN_REVERSION_STRENGTH;
          price = nextPrice(price, scaledVol, drift);
          docs.push({
            symbol: ticker.symbol,
            price: Number(price.toFixed(2)),
            timestamp: new Date(now - i * tier.stepMs),
          });
        }
      }
    }

    if (docs.length === 0) {
      const total = await this.historyModel.countDocuments();
      this.logger.log(`History already backfilled (${total} points present)`);
      return;
    }

    // Chunk the insert — 5y of daily + 60d of hourly + 24h of minute
    // data per symbol × 6 symbols = ~25k docs, which is fine for one
    // insertMany but we split into 5k batches so Mongo's payload limit
    // stays comfortably out of reach.
    const BATCH = 5000;
    for (let i = 0; i < docs.length; i += BATCH) {
      await this.historyModel.insertMany(docs.slice(i, i + BATCH));
    }
    this.logger.log(
      `✅ Backfilled ${docs.length} historical price points across ${
        new Set(docs.map((d) => d.symbol)).size
      } symbol(s) (minute + hourly + daily tiers)`,
    );
  }

  async getAll() {
    const cached = await this.cache.get<unknown>(TICKERS_CACHE_KEY);
    if (cached) return cached;

    const tickers = await this.tickerModel
      .find({ is_active: true })
      .sort({ symbol: 1 });
    const result = tickers.map((t) => t.toJSON());
    await this.cache.set(TICKERS_CACHE_KEY, result, TICKERS_CACHE_TTL_MS);
    return result;
  }

  async getBySymbol(symbol: string) {
    const upper = symbol.toUpperCase();
    const ticker = await this.tickerModel.findOne({ symbol: upper });
    if (!ticker) {
      throw new NotFoundException(`Ticker ${upper} not found`);
    }
    const last = await this.historyModel
      .findOne({ symbol: upper })
      .sort({ timestamp: -1 })
      .lean();

    return {
      ticker: ticker.toJSON(),
      lastPrice: last?.price ?? ticker.base_price,
      lastTimestamp: last?.timestamp ?? new Date(),
    };
  }

  async getHistory(symbol: string, query: HistoryQueryDto) {
    const upper = symbol.toUpperCase();

    // Two modes: custom window via from/to, or a preset range.
    let since: Date;
    let until: Date;
    let interval: HistoryInterval;
    let cacheKey: string;

    if (query.from && query.to) {
      since = new Date(query.from);
      until = new Date(query.to);
      if (
        Number.isNaN(since.getTime()) ||
        Number.isNaN(until.getTime()) ||
        since >= until
      ) {
        throw new NotFoundException('Invalid from/to window');
      }
      // Pick an interval that gives a reasonable point density for the
      // requested custom window, unless the caller explicitly asked.
      const spanMs = until.getTime() - since.getTime();
      interval = query.interval ?? this.pickIntervalForSpan(spanMs);
      cacheKey = `history:${upper}:custom:${since.toISOString()}:${until.toISOString()}:${interval}`;
    } else {
      const range = query.range ?? '1h';
      const rangeMs = this.parseRangeMs(range);
      until = new Date();
      since = new Date(until.getTime() - rangeMs);
      // Default interval per range, tuned for ~60–200 points on the chart.
      interval = query.interval ?? this.defaultIntervalFor(range);
      cacheKey = `history:${upper}:${range}:${interval}`;
    }

    const cached = await this.cache.get<unknown>(cacheKey);
    if (cached) return cached;

    const exists = await this.tickerModel.exists({ symbol: upper });
    if (!exists) throw new NotFoundException(`Ticker ${upper} not found`);

    const intervalMs = this.parseIntervalMs(interval);

    const raw = await this.historyModel
      .find({ symbol: upper, timestamp: { $gte: since, $lte: until } })
      .sort({ timestamp: 1 })
      .lean();

    // Bucket raw points into the requested interval (avg per bucket)
    const buckets = new Map<
      number,
      { sum: number; count: number; ts: number }
    >();
    for (const point of raw) {
      const bucketTs =
        Math.floor(point.timestamp.getTime() / intervalMs) * intervalMs;
      const existing = buckets.get(bucketTs);
      if (existing) {
        existing.sum += point.price;
        existing.count += 1;
      } else {
        buckets.set(bucketTs, { sum: point.price, count: 1, ts: bucketTs });
      }
    }

    const result = Array.from(buckets.values())
      .sort((a, b) => a.ts - b.ts)
      .map((b) => ({
        timestamp: new Date(b.ts).toISOString(),
        price: Number((b.sum / b.count).toFixed(2)),
      }));

    await this.cache.set(cacheKey, result, HISTORY_CACHE_TTL_MS);
    return result;
  }

  /** Used by Step 6 simulator to seed in-memory state */
  async getActiveTickers() {
    return this.tickerModel.find({ is_active: true }).lean();
  }

  /** Cheap existence check used by AlertService when validating user input */
  async tickerExists(symbol: string): Promise<boolean> {
    const upper = symbol.toUpperCase();
    const found = await this.tickerModel.exists({ symbol: upper });
    return Boolean(found);
  }

  /** Used by Step 6 simulator to persist live ticks in batches */
  async appendHistory(
    docs: { symbol: string; price: number; timestamp: Date }[],
  ) {
    if (docs.length === 0) return;
    await this.historyModel.insertMany(docs);
  }

  private parseRangeMs(range: HistoryRange): number {
    const HOUR = 60 * 60 * 1000;
    const DAY = 24 * HOUR;
    switch (range) {
      case '1h':
        return HOUR;
      case '1d':
        return DAY;
      case '1w':
        return 7 * DAY;
      case '1mo':
        return 30 * DAY;
      case '1y':
        return 365 * DAY;
      case '5y':
        return 5 * 365 * DAY;
    }
  }

  private parseIntervalMs(interval: HistoryInterval): number {
    switch (interval) {
      case '1m':
        return 60 * 1000;
      case '5m':
        return 5 * 60 * 1000;
      case '1h':
        return 60 * 60 * 1000;
      case '1d':
        return 24 * 60 * 60 * 1000;
    }
  }

  /** Default interval for a preset range, tuned to render ~50–200 points. */
  private defaultIntervalFor(range: HistoryRange): HistoryInterval {
    switch (range) {
      case '1h':
        return '1m';
      case '1d':
        return '5m';
      case '1w':
        return '1h';
      case '1mo':
        return '1h';
      case '1y':
        return '1d';
      case '5y':
        return '1d';
    }
  }

  /** Pick a bucket size that keeps custom-range queries under ~500 points. */
  private pickIntervalForSpan(spanMs: number): HistoryInterval {
    const HOUR = 60 * 60 * 1000;
    const DAY = 24 * HOUR;
    if (spanMs <= 2 * HOUR) return '1m';
    if (spanMs <= 2 * DAY) return '5m';
    if (spanMs <= 30 * DAY) return '1h';
    return '1d';
  }
}
